import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/home.module.scss';

import logoImg from '../../public/logo.svg';

import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';

import Link from 'next/link';

export default function Home() {
	return (
		<>
			<Head>
				<title>Sujeito Pizzaria - Faça seu login</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<section className={`home ${styles.home}`}>
					<div className={`container ${styles.container}`}>
						<div className={styles.content}>
							<div className={styles.logo}>
								<Image
									src={logoImg}
									alt="Logo Sujeito Pizzaria"
								/>
							</div>

							<div className={styles.login}>
								<form action="">
									<Input
										placeholder="Digite seu e-mail"
										type="text"
									/>
									<Input
										placeholder="Digite sua senha"
										type="password"
									/>

									<Button type="submit" loading={false}>
										Acessar
									</Button>
								</form>

								<Link href="/signup" className={styles.link}>
									Não possui uma conta? Cadastre-se
								</Link>
							</div>
						</div>
					</div>
				</section>
			</main>
		</>
	);
}
